// <auto-generated />
using System;
using HotelAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAPI.Migrations
{
    [DbContext(typeof(HotelDBContext))]
    [Migration("20250523081129_UdpatedCheckInOut")]
    partial class UdpatedCheckInOut
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelAPI.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Paris",
                            Country = "France",
                            Email = "eiffel@hotel.com",
                            Name = "Eiffel Hotel",
                            Phone = "+33 123456789",
                            StreetName = "Rue de Paris",
                            StreetNo = "10",
                            Zipcode = 75001
                        },
                        new
                        {
                            ID = 2,
                            City = "Paris",
                            Country = "France",
                            Email = "louvre@hotel.com",
                            Name = "Louvre Inn",
                            Phone = "+33 987654321",
                            StreetName = "Rue de Louvre",
                            StreetNo = "22B",
                            Zipcode = 75002
                        },
                        new
                        {
                            ID = 3,
                            City = "London",
                            Country = "UK",
                            Email = "bigben@hotel.com",
                            Name = "Big Ben Hotel",
                            Phone = "+44 123456789",
                            StreetName = "Westminster Rd",
                            StreetNo = "5",
                            Zipcode = 10001
                        },
                        new
                        {
                            ID = 4,
                            City = "London",
                            Country = "UK",
                            Email = "thames@hotel.com",
                            Name = "Thames View Inn",
                            Phone = "+44 987654321",
                            StreetName = "River St",
                            StreetNo = "18A",
                            Zipcode = 10002
                        },
                        new
                        {
                            ID = 5,
                            City = "Berlin",
                            Country = "Germany",
                            Email = "central@hotel.com",
                            Name = "Berlin Central Hotel",
                            Phone = "+49 123456789",
                            StreetName = "Hauptstrasse",
                            StreetNo = "77",
                            Zipcode = 10115
                        },
                        new
                        {
                            ID = 6,
                            City = "Berlin",
                            Country = "Germany",
                            Email = "brandenburg@hotel.com",
                            Name = "Brandenburger Inn",
                            Phone = "+49 987654321",
                            StreetName = "Torstrasse",
                            StreetNo = "66B",
                            Zipcode = 10117
                        });
                });

            modelBuilder.Entity("HotelAPI.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HotelID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 1,
                            Price = 100.0,
                            Rating = 4.2000000000000002,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 2,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 1,
                            Price = 150.0,
                            Rating = 4.5,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 3,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 1,
                            Price = 300.0,
                            Rating = 4.7999999999999998,
                            Type = "Suite"
                        },
                        new
                        {
                            ID = 4,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 2,
                            Price = 90.0,
                            Rating = 3.7999999999999998,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 5,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 2,
                            Price = 140.0,
                            Rating = 4.0,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 6,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 2,
                            Price = 280.0,
                            Rating = 4.5999999999999996,
                            Type = "Suite"
                        },
                        new
                        {
                            ID = 7,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 3,
                            Price = 110.0,
                            Rating = 4.0,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 8,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 3,
                            Price = 160.0,
                            Rating = 4.0999999999999996,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 9,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 3,
                            Price = 310.0,
                            Rating = 4.9000000000000004,
                            Type = "Suite"
                        },
                        new
                        {
                            ID = 10,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 4,
                            Price = 95.0,
                            Rating = 3.8999999999999999,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 11,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 4,
                            Price = 145.0,
                            Rating = 4.2000000000000002,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 12,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 4,
                            Price = 295.0,
                            Rating = 4.7000000000000002,
                            Type = "Suite"
                        },
                        new
                        {
                            ID = 13,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 5,
                            Price = 105.0,
                            Rating = 4.2999999999999998,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 14,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 5,
                            Price = 155.0,
                            Rating = 4.4000000000000004,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 15,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 5,
                            Price = 320.0,
                            Rating = 4.9000000000000004,
                            Type = "Suite"
                        },
                        new
                        {
                            ID = 16,
                            Capacity = 1,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 6,
                            Price = 98.0,
                            Rating = 4.0999999999999996,
                            Type = "Single"
                        },
                        new
                        {
                            ID = 17,
                            Capacity = 2,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 6,
                            Price = 142.0,
                            Rating = 4.2999999999999998,
                            Type = "Double"
                        },
                        new
                        {
                            ID = 18,
                            Capacity = 4,
                            CheckIn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelID = 6,
                            Price = 305.0,
                            Rating = 4.5999999999999996,
                            Type = "Suite"
                        });
                });

            modelBuilder.Entity("HotelAPI.Models.Room", b =>
                {
                    b.HasOne("HotelAPI.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelAPI.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
